const express = require('express');
const axios = require('axios');
const app = express();
const port = 3000;

const JUP_API_KEY = 'jup_45628fb7a2a0fae5631fe113c68ee7bb117bb35a8913327af2b83362cbcb6970';
const HEADERS = { 'x-api-key': JUP_API_KEY };

app.use(express.static('public'));

app.get('/api/analyze/:mint', async (req, res) => {
    const mint = req.params.mint;
    try {
        const [price, token] = await Promise.all([
            axios.get(`https://api.jup.ag/price/v3?ids=${mint}`, { headers: HEADERS }),
            axios.get(`https://api.jup.ag/tokens/v1/token/${mint}`, { headers: HEADERS })
        ]);

        // AI Thesis Generation Logic could be added here via OpenRouter
        res.json({
            price: price.data.data[mint],
            token: token.data,
            thesis: "Analysis generated by JupiterMind AI engine."
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.listen(port, () => console.log(`JupiterMind Solana App listening on port ${port}`));
